Напишите функцию, реализующую матричное умножение. Для этого реализуйте функцию matrix_multiplication:

import numpy as np
import typing as tp

def matrix_multiplication(A: np.ndarray, B: np.ndarray) -> np.ndarray:    
    return ...

При вычислении разрешается создавать объекты размерности три и использовать только:

простые стандартные поэлементные векторно-арифметические операции над numpy.array (поэлементная сумма, поэлементное произведение и т.д.)
стандартные агрегирующие арифметические операции над numpy.array (например, сумма вдоль оси)
любые операции изменения формы массива (например, транспонирование, добавление осей).

Запрещается пользоваться:

циклами
list comprehension
функциями, реализующими матричное умножение, например, numpy.dot, операция @, операция умножения в классе numpy.matrix, суммы Эйнштейна и прочие.
функциями вида map, apply
функциями вида fromfunction, apply_along_axis

In [25]:
import numpy as np
import typing as tp

def matrix_multiplication(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    A = np.repeat(A[:, :, np.newaxis], B.shape[1], axis=2) 
    print(A, '\n')
    
    return np.array([np.sum(a_row*b_col) for a_row in A for b_col in B.T])

A = np.array([[-1,1]]) # [3,4,5]
B = np.array([[8, 1],[-1, 2]])
print(A)
print(B)
print(A@B, '\n')
print(matrix_multiplication(A,B))

[[-1  1]]
[[ 8  1]
 [-1  2]]
[[-9  1]] 

[[[-1 -1]
  [ 1  1]]] 

[0 0]


In [ ]:
# A1 = A.copy()
# A2 = A.copy()

# A1[0,:] *= B[0].T
# A1[1,:] *= B[0].T
# A1 = np.sum(A1, axis=1)
# display(A1)

# A2[0,:] *= B[1].T
# A2[1,:] *= B[1].T
# A2 = np.sum(A2, axis=1)
# display(A2)

# ans = np.vstack([A1, A2]).T
# ans

In [143]:
A = np.array([[-1,0],[ 3,2]])
B = np.array([[ 2,6],[-1,7]])
print(A@B)
# [-1 0] @ [ 2 6] = [-2 6] , некая ЛК столлбцов: sum(a_row1 * b_col1) = a[0][0]*b[0][0] + a[0][1]*b[1][0]
# [ 3 2]   [-1 7]   [4 32]                       sum(a_row2 * b_col1)   a[1][0]*b[0][0] + a[1][1]*b[1][0]

print(A * B)
print(np.sum(A.T * B, axis=1))
# print((A.T * B)[1])

[[-2 -6]
 [ 4 32]]
[[-2  0]
 [-3 14]]
[16 14]
